version: "3"

services:
  beammp-server:
    image: rouhim/beammp-server
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      # Game server parameter
      - BEAMMP_PRIVATE
      - BEAMMP_CARS
      - BEAMMP_MAX_PLAYERS
      - BEAMMP_MAP
      - BEAMMP_NAME
      - BEAMMP_DESC
      - BEAMMP_PORT
      - BEAMMP_DEBUG
      - BEAMMP_AUTH_KEY
    volumes:
      # Map a custom server toml file, enable this only if needed
      #- ./ServerConfig.toml:/beammp/ServerConfig.toml
      # Just move all the client mods you want to add into this folder
      - ./client-mods:/beammp/Resources/Client
      # All server mods belong here
      - ./server-mods:/beammp/Resources/Server
    ports:
      - "${BEAMMP_PORT}:${BEAMMP_PORT}/tcp"
      - "${BEAMMP_PORT}:${BEAMMP_PORT}/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"