version: "3"

services:
  beammp-server:
    image: rouhim/beammp-server
    build:
      context: .
    environment:      
      # Game server parameter
      - PRIVATE
      - DEBUG
      - CARS
      - MAX_PLAYERS
      - MAP
      - NAME
      - DESC
      - AUTH_KEY
    volumes:
      # Simply slide any mod you want to add in that folder
      - ./mods:/beammp/Resources/Client
    ports:
      - 30814:30814/tcp
      - 30814:30814/udp
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
