# This builds the latest stable release version of beammp
name: Release Pipe
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: "0 0 * * 0" # weekly at sunday night

env:
  CONTAINER_FILE: ./glibc.Containerfile
  IMAGE_NAME: rouhim/beammp-server
  TAGS: latest

jobs:

  check-containerfile:
    name: Check container file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  build-container-image:
    needs: [ check-containerfile ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          archs: amd64
          oci: true
          containerfiles: |
            ${{ env.CONTAINER_FILE }}


#  build-docker-image:
#    runs-on: ubuntu-latest
#    env:
#      DOCKER_BUILDKIT: 1 # use the new docker build backend
#      BEAMMP_AUTH_KEY: ${{ secrets.BEAMMP_AUTH_KEY }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#      - name: Build images
#        # 1. create docker buildx builder instance
#        # 2. build for all platforms
#        # 3. load amd64 image in: docker images
#        run: |
#          docker buildx create --use
#          docker buildx build -f glibc.Dockerfile -t rouhim/beammp-server --platform linux/amd64 .
#          docker buildx build -f glibc.Dockerfile --load -t rouhim/beammp-server .
#      #          docker buildx build -t rouhim/beammp-server --platform linux/amd64,linux/arm64,linux/arm/v7 .
#      #          docker buildx build --load -t rouhim/beammp-server .
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: 'rouhim/beammp-server'
#          ignore-unfixed: true
#          severity: 'CRITICAL,HIGH'
#          exit-code: '1'
#      - name: Test the built image
#        env:
#          BEAMMP_AUTH_KEY: ${{ secrets.BEAMMP_AUTH_KEY }}
#        run: |
#          bash test-image.sh rouhim/beammp-server
#      - name: Push images
#        run: |
#          docker buildx build -f glibc.Dockerfile -t rouhim/beammp-server --platform linux/amd64 --push .
#      #          docker buildx build -t rouhim/beammp-server --platform linux/amd64,linux/arm64,linux/arm/v7 --push .
#      - name: Update docker hub description
#        uses: peter-evans/dockerhub-description@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          repository: rouhim/beammp-server
