# This is a basic workflow to help you get started with Actions

name: CI
on:  
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:  
  build-specific:    
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: |          
          VERSION=1.20
          docker-compose build
          docker-compose push
          VERSION=latest
          docker-compose build
          docker-compose push
