# This builds the latest stable release version of beammp
name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1 # use the new docker build backend
      BEAMMP_AUTH_KEY: ${{ secrets.BEAMMP_AUTH_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Test the built image
        run: |
          env
          echo "${{ secrets.BEAMMP_AUTH_KEY }}"
          docker pull rouhim/beammp-server
          bash test-image.sh
